# baseURL: https://tech.cloudmt.co.kr # 추후 수정 필요
title: CLOUDMATE Tech
theme:
  - github.com/jonathanjanssens/hugo-casper3
permalinks: 
  post: /:2006/:01/:02/:filename
taxonomies:
  author: authors
  tag: tags
  category: categories

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: cloudmt.co.kr
          url: https://cloudmt.co.kr
          weight: 20

googleAnalytics: UA-146594086-2
hasCJKLanguage: true
params:
  description: 클라우드메이트는 고객의 비즈니스 환경을 우선으로 생각하고, 사용자로서의 직접 경험을 공유합니다.
  logo: /assets/images/CMLOGO_WHITE.png
  assets:
        favicon: /assets/favicon.ico
  
  DateFormat: 2006. 01. 02.
  facebook: https://fb.me/cloudmatekr
  github: https://github.com/mate365
  mainSections:
    - post
  mainButtons:
    - name: 채용 정보 보기
      url: https://recruit.cloudmt.co.kr
