baseURL: https://tech.cloudmt.co.kr/
disablePathToLower: true
languageCode: ko-kr
title: CloudMate Tech
theme:
  - github.com/theNewDynamic/gohugo-theme-ananke
permalinks: 
  post: /:2006/:01/:02/:filename
params:
  site_logo: /assets/images/logo-tech.png
  featured_image: /assets/images/img4.jpg
  background_color_class: bg-grey