baseURL: /
title: CLOUDMATE Tech
theme:
  - github.com/jonathanjanssens/hugo-casper3
permalinks: 
  post: /:2006/:01/:02/:filename
taxonomies:
  author: authors
  tag: tags
  category: categories

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: cloudmt.co.kr
          url: https://cloudmt.co.kr
          weight: 20
related:
  includeNewer: false
  indices:
  - category: categories
    weight: 100
  - name: date
    weight: 10
  threshold: 80
  toLower: false

googleAnalytics: UA-146594086-2
hasCJKLanguage: true
paginate: 10
params:
  description: CLOUDMATE Tech Blog
  logo: /assets/images/CMLOGO_WHITE.png
  assets:
        favicon: /assets/favicon.ico
  
  DateFormat: 2006. 01. 02.
  facebook: https://fb.me/cloudmatekr
  github: https://github.com/mate365
  mainSections:
    - post
  mainButtons:
    - name: We Are Hiring!
      url: https://recruit.cloudmt.co.kr
